version = 0.1

[default.deploy.parameters]
stack_name = "mwaa-serverless-mcp"
resolve_s3 = true
s3_prefix = "mwaa-serverless-mcp"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
