"""
MWAA Serverless supported operators and YAML schema.

Operators sourced from the official allowlist.
Schema from the DAG YAML Schema (draft-07).
"""

SUPPORTED_OPERATORS = {
    # ── Other ──
    "EmptyOperator": "airflow.operators.empty.EmptyOperator",
    # ── S3 ──
    "S3CreateBucketOperator": "airflow.providers.amazon.aws.operators.s3.S3CreateBucketOperator",
    "S3DeleteBucketOperator": "airflow.providers.amazon.aws.operators.s3.S3DeleteBucketOperator",
    "S3GetBucketTaggingOperator": "airflow.providers.amazon.aws.operators.s3.S3GetBucketTaggingOperator",
    "S3PutBucketTaggingOperator": "airflow.providers.amazon.aws.operators.s3.S3PutBucketTaggingOperator",
    "S3DeleteBucketTaggingOperator": "airflow.providers.amazon.aws.operators.s3.S3DeleteBucketTaggingOperator",
    "S3CopyObjectOperator": "airflow.providers.amazon.aws.operators.s3.S3CopyObjectOperator",
    "S3CreateObjectOperator": "airflow.providers.amazon.aws.operators.s3.S3CreateObjectOperator",
    "S3DeleteObjectsOperator": "airflow.providers.amazon.aws.operators.s3.S3DeleteObjectsOperator",
    "S3ListOperator": "airflow.providers.amazon.aws.operators.s3.S3ListOperator",
    "S3ListPrefixesOperator": "airflow.providers.amazon.aws.operators.s3.S3ListPrefixesOperator",
    "S3KeySensor": "airflow.providers.amazon.aws.sensors.s3.S3KeySensor",
    "S3KeysUnchangedSensor": "airflow.providers.amazon.aws.sensors.s3.S3KeysUnchangedSensor",
    # ── Glue ──
    "GlueJobOperator": "airflow.providers.amazon.aws.operators.glue.GlueJobOperator",
    "GlueDataQualityOperator": "airflow.providers.amazon.aws.operators.glue.GlueDataQualityOperator",
    "GlueDataQualityRuleSetEvaluationRunOperator": "airflow.providers.amazon.aws.operators.glue.GlueDataQualityRuleSetEvaluationRunOperator",
    "GlueDataQualityRuleRecommendationRunOperator": "airflow.providers.amazon.aws.operators.glue.GlueDataQualityRuleRecommendationRunOperator",
    "GlueDataBrewStartJobOperator": "airflow.providers.amazon.aws.operators.glue_databrew.GlueDataBrewStartJobOperator",
    "GlueCrawlerOperator": "airflow.providers.amazon.aws.operators.glue_crawler.GlueCrawlerOperator",
    "GlueJobSensor": "airflow.providers.amazon.aws.sensors.glue.GlueJobSensor",
    "GlueDataQualityRuleSetEvaluationRunSensor": "airflow.providers.amazon.aws.sensors.glue.GlueDataQualityRuleSetEvaluationRunSensor",
    "GlueDataQualityRuleRecommendationRunSensor": "airflow.providers.amazon.aws.sensors.glue.GlueDataQualityRuleRecommendationRunSensor",
    "GlueCatalogPartitionSensor": "airflow.providers.amazon.aws.sensors.glue_catalog_partition.GlueCatalogPartitionSensor",
    "GlueCrawlerSensor": "airflow.providers.amazon.aws.sensors.glue_crawler.GlueCrawlerSensor",
    # ── Athena ──
    "AthenaOperator": "airflow.providers.amazon.aws.operators.athena.AthenaOperator",
    "AthenaSensor": "airflow.providers.amazon.aws.sensors.athena.AthenaSensor",
    # ── Bedrock ──
    "BedrockInvokeModelOperator": "airflow.providers.amazon.aws.operators.bedrock.BedrockInvokeModelOperator",
    "BedrockCustomizeModelOperator": "airflow.providers.amazon.aws.operators.bedrock.BedrockCustomizeModelOperator",
    "BedrockCreateProvisionedModelThroughputOperator": "airflow.providers.amazon.aws.operators.bedrock.BedrockCreateProvisionedModelThroughputOperator",
    "BedrockCreateKnowledgeBaseOperator": "airflow.providers.amazon.aws.operators.bedrock.BedrockCreateKnowledgeBaseOperator",
    "BedrockCreateDataSourceOperator": "airflow.providers.amazon.aws.operators.bedrock.BedrockCreateDataSourceOperator",
    "BedrockIngestDataOperator": "airflow.providers.amazon.aws.operators.bedrock.BedrockIngestDataOperator",
    "BedrockRaGOperator": "airflow.providers.amazon.aws.operators.bedrock.BedrockRaGOperator",
    "BedrockRetrieveOperator": "airflow.providers.amazon.aws.operators.bedrock.BedrockRetrieveOperator",
    "BedrockBaseSensor": "airflow.providers.amazon.aws.sensors.bedrock.BedrockBaseSensor",
    "BedrockCustomizeModelCompletedSensor": "airflow.providers.amazon.aws.sensors.bedrock.BedrockCustomizeModelCompletedSensor",
    "BedrockProvisionModelThroughputCompletedSensor": "airflow.providers.amazon.aws.sensors.bedrock.BedrockProvisionModelThroughputCompletedSensor",
    "BedrockKnowledgeBaseActiveSensor": "airflow.providers.amazon.aws.sensors.bedrock.BedrockKnowledgeBaseActiveSensor",
    "BedrockIngestionJobSensor": "airflow.providers.amazon.aws.sensors.bedrock.BedrockIngestionJobSensor",
    # ── Lambda ──
    "LambdaCreateFunctionOperator": "airflow.providers.amazon.aws.operators.lambda_function.LambdaCreateFunctionOperator",
    "LambdaInvokeFunctionOperator": "airflow.providers.amazon.aws.operators.lambda_function.LambdaInvokeFunctionOperator",
    "LambdaFunctionStateSensor": "airflow.providers.amazon.aws.sensors.lambda_function.LambdaFunctionStateSensor",
    # ── Step Functions ──
    "StepFunctionStartExecutionOperator": "airflow.providers.amazon.aws.operators.step_function.StepFunctionStartExecutionOperator",
    "StepFunctionGetExecutionOutputOperator": "airflow.providers.amazon.aws.operators.step_function.StepFunctionGetExecutionOutputOperator",
    "StepFunctionExecutionSensor": "airflow.providers.amazon.aws.sensors.step_function.StepFunctionExecutionSensor",
    # ── EMR ──
    "EmrAddStepsOperator": "airflow.providers.amazon.aws.operators.emr.EmrAddStepsOperator",
    "EmrStartNotebookExecutionOperator": "airflow.providers.amazon.aws.operators.emr.EmrStartNotebookExecutionOperator",
    "EmrStopNotebookExecutionOperator": "airflow.providers.amazon.aws.operators.emr.EmrStopNotebookExecutionOperator",
    "EmrEksCreateClusterOperator": "airflow.providers.amazon.aws.operators.emr.EmrEksCreateClusterOperator",
    "EmrContainerOperator": "airflow.providers.amazon.aws.operators.emr.EmrContainerOperator",
    "EmrCreateJobFlowOperator": "airflow.providers.amazon.aws.operators.emr.EmrCreateJobFlowOperator",
    "EmrModifyClusterOperator": "airflow.providers.amazon.aws.operators.emr.EmrModifyClusterOperator",
    "EmrTerminateJobFlowOperator": "airflow.providers.amazon.aws.operators.emr.EmrTerminateJobFlowOperator",
    "EmrServerlessCreateApplicationOperator": "airflow.providers.amazon.aws.operators.emr.EmrServerlessCreateApplicationOperator",
    "EmrServerlessStartJobOperator": "airflow.providers.amazon.aws.operators.emr.EmrServerlessStartJobOperator",
    "EmrServerlessStopApplicationOperator": "airflow.providers.amazon.aws.operators.emr.EmrServerlessStopApplicationOperator",
    "EmrServerlessDeleteApplicationOperator": "airflow.providers.amazon.aws.operators.emr.EmrServerlessDeleteApplicationOperator",
    "EmrBaseSensor": "airflow.providers.amazon.aws.sensors.emr.EmrBaseSensor",
    "EmrServerlessJobSensor": "airflow.providers.amazon.aws.sensors.emr.EmrServerlessJobSensor",
    "EmrServerlessApplicationSensor": "airflow.providers.amazon.aws.sensors.emr.EmrServerlessApplicationSensor",
    "EmrContainerSensor": "airflow.providers.amazon.aws.sensors.emr.EmrContainerSensor",
    "EmrNotebookExecutionSensor": "airflow.providers.amazon.aws.sensors.emr.EmrNotebookExecutionSensor",
    "EmrJobFlowSensor": "airflow.providers.amazon.aws.sensors.emr.EmrJobFlowSensor",
    "EmrStepSensor": "airflow.providers.amazon.aws.sensors.emr.EmrStepSensor",
    # ── Batch ──
    "BatchOperator": "airflow.providers.amazon.aws.operators.batch.BatchOperator",
    "BatchCreateComputeEnvironmentOperator": "airflow.providers.amazon.aws.operators.batch.BatchCreateComputeEnvironmentOperator",
    "BatchSensor": "airflow.providers.amazon.aws.sensors.batch.BatchSensor",
    "BatchComputeEnvironmentSensor": "airflow.providers.amazon.aws.sensors.batch.BatchComputeEnvironmentSensor",
    "BatchJobQueueSensor": "airflow.providers.amazon.aws.sensors.batch.BatchJobQueueSensor",
    # ── ECS ──
    "EcsBaseOperator": "airflow.providers.amazon.aws.operators.ecs.EcsBaseOperator",
    "EcsCreateClusterOperator": "airflow.providers.amazon.aws.operators.ecs.EcsCreateClusterOperator",
    "EcsDeleteClusterOperator": "airflow.providers.amazon.aws.operators.ecs.EcsDeleteClusterOperator",
    "EcsDeregisterTaskDefinitionOperator": "airflow.providers.amazon.aws.operators.ecs.EcsDeregisterTaskDefinitionOperator",
    "EcsRegisterTaskDefinitionOperator": "airflow.providers.amazon.aws.operators.ecs.EcsRegisterTaskDefinitionOperator",
    "EcsRunTaskOperator": "airflow.providers.amazon.aws.operators.ecs.EcsRunTaskOperator",
    "EcsBaseSensor": "airflow.providers.amazon.aws.sensors.ecs.EcsBaseSensor",
    "EcsClusterStateSensor": "airflow.providers.amazon.aws.sensors.ecs.EcsClusterStateSensor",
    "EcsTaskDefinitionStateSensor": "airflow.providers.amazon.aws.sensors.ecs.EcsTaskDefinitionStateSensor",
    "EcsTaskStateSensor": "airflow.providers.amazon.aws.sensors.ecs.EcsTaskStateSensor",
    # ── EKS ──
    "EksCreateClusterOperator": "airflow.providers.amazon.aws.operators.eks.EksCreateClusterOperator",
    "EksCreateNodegroupOperator": "airflow.providers.amazon.aws.operators.eks.EksCreateNodegroupOperator",
    "EksCreateFargateProfileOperator": "airflow.providers.amazon.aws.operators.eks.EksCreateFargateProfileOperator",
    "EksDeleteClusterOperator": "airflow.providers.amazon.aws.operators.eks.EksDeleteClusterOperator",
    "EksDeleteNodegroupOperator": "airflow.providers.amazon.aws.operators.eks.EksDeleteNodegroupOperator",
    "EksDeleteFargateProfileOperator": "airflow.providers.amazon.aws.operators.eks.EksDeleteFargateProfileOperator",
    "EksPodOperator": "airflow.providers.amazon.aws.operators.eks.EksPodOperator",
    "EksBaseSensor": "airflow.providers.amazon.aws.sensors.eks.EksBaseSensor",
    "EksClusterStateSensor": "airflow.providers.amazon.aws.sensors.eks.EksClusterStateSensor",
    "EksFargateProfileStateSensor": "airflow.providers.amazon.aws.sensors.eks.EksFargateProfileStateSensor",
    "EksNodegroupStateSensor": "airflow.providers.amazon.aws.sensors.eks.EksNodegroupStateSensor",
    # ── CloudFormation ──
    "CloudFormationCreateStackOperator": "airflow.providers.amazon.aws.operators.cloud_formation.CloudFormationCreateStackOperator",
    "CloudFormationDeleteStackOperator": "airflow.providers.amazon.aws.operators.cloud_formation.CloudFormationDeleteStackOperator",
    "CloudFormationCreateStackSensor": "airflow.providers.amazon.aws.sensors.cloud_formation.CloudFormationCreateStackSensor",
    "CloudFormationDeleteStackSensor": "airflow.providers.amazon.aws.sensors.cloud_formation.CloudFormationDeleteStackSensor",
    # ── SageMaker ──
    "SageMakerNotebookOperator": "airflow.providers.amazon.aws.operators.sagemaker_unified_studio.SageMakerNotebookOperator",
    "SageMakerBaseOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerBaseOperator",
    "SageMakerProcessingOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerProcessingOperator",
    "SageMakerEndpointConfigOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerEndpointConfigOperator",
    "SageMakerEndpointOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerEndpointOperator",
    "SageMakerTransformOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerTransformOperator",
    "SageMakerTuningOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerTuningOperator",
    "SageMakerModelOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerModelOperator",
    "SageMakerTrainingOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerTrainingOperator",
    "SageMakerDeleteModelOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerDeleteModelOperator",
    "SageMakerStartPipelineOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerStartPipelineOperator",
    "SageMakerStopPipelineOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerStopPipelineOperator",
    "SageMakerRegisterModelVersionOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerRegisterModelVersionOperator",
    "SageMakerAutoMLOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerAutoMLOperator",
    "SageMakerCreateExperimentOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerCreateExperimentOperator",
    "SageMakerCreateNotebookOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerCreateNotebookOperator",
    "SageMakerStopNotebookOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerStopNotebookOperator",
    "SageMakerDeleteNotebookOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerDeleteNotebookOperator",
    "SageMakerStartNoteBookOperator": "airflow.providers.amazon.aws.operators.sagemaker.SageMakerStartNoteBookOperator",
    "SageMakerBaseSensor": "airflow.providers.amazon.aws.sensors.sagemaker.SageMakerBaseSensor",
    "SageMakerEndpointSensor": "airflow.providers.amazon.aws.sensors.sagemaker.SageMakerEndpointSensor",
    "SageMakerTransformSensor": "airflow.providers.amazon.aws.sensors.sagemaker.SageMakerTransformSensor",
    "SageMakerTuningSensor": "airflow.providers.amazon.aws.sensors.sagemaker.SageMakerTuningSensor",
    "SageMakerTrainingSensor": "airflow.providers.amazon.aws.sensors.sagemaker.SageMakerTrainingSensor",
    "SageMakerPipelineSensor": "airflow.providers.amazon.aws.sensors.sagemaker.SageMakerPipelineSensor",
    "SageMakerAutoMLSensor": "airflow.providers.amazon.aws.sensors.sagemaker.SageMakerAutoMLSensor",
    "SageMakerProcessingSensor": "airflow.providers.amazon.aws.sensors.sagemaker.SageMakerProcessingSensor",
    "SageMakerNotebookSensor": "airflow.providers.amazon.aws.sensors.sagemaker_unified_studio.SageMakerNotebookSensor",
    # ── RDS ──
    "RdsBaseOperator": "airflow.providers.amazon.aws.operators.rds.RdsBaseOperator",
    "RdsCreateDbSnapshotOperator": "airflow.providers.amazon.aws.operators.rds.RdsCreateDbSnapshotOperator",
    "RdsCopyDbSnapshotOperator": "airflow.providers.amazon.aws.operators.rds.RdsCopyDbSnapshotOperator",
    "RdsDeleteDbSnapshotOperator": "airflow.providers.amazon.aws.operators.rds.RdsDeleteDbSnapshotOperator",
    "RdsStartExportTaskOperator": "airflow.providers.amazon.aws.operators.rds.RdsStartExportTaskOperator",
    "RdsCancelExportTaskOperator": "airflow.providers.amazon.aws.operators.rds.RdsCancelExportTaskOperator",
    "RdsCreateEventSubscriptionOperator": "airflow.providers.amazon.aws.operators.rds.RdsCreateEventSubscriptionOperator",
    "RdsDeleteEventSubscriptionOperator": "airflow.providers.amazon.aws.operators.rds.RdsDeleteEventSubscriptionOperator",
    "RdsCreateDbInstanceOperator": "airflow.providers.amazon.aws.operators.rds.RdsCreateDbInstanceOperator",
    "RdsDeleteDbInstanceOperator": "airflow.providers.amazon.aws.operators.rds.RdsDeleteDbInstanceOperator",
    "RdsStartDbOperator": "airflow.providers.amazon.aws.operators.rds.RdsStartDbOperator",
    "RdsStopDbOperator": "airflow.providers.amazon.aws.operators.rds.RdsStopDbOperator",
    "RdsBaseSensor": "airflow.providers.amazon.aws.sensors.rds.RdsBaseSensor",
    "RdsSnapshotExistenceSensor": "airflow.providers.amazon.aws.sensors.rds.RdsSnapshotExistenceSensor",
    "RdsExportTaskExistenceSensor": "airflow.providers.amazon.aws.sensors.rds.RdsExportTaskExistenceSensor",
    "RdsDbSensor": "airflow.providers.amazon.aws.sensors.rds.RdsDbSensor",
    # ── Redshift ──
    "RedshiftCreateClusterOperator": "airflow.providers.amazon.aws.operators.redshift_cluster.RedshiftCreateClusterOperator",
    "RedshiftCreateClusterSnapshotOperator": "airflow.providers.amazon.aws.operators.redshift_cluster.RedshiftCreateClusterSnapshotOperator",
    "RedshiftDeleteClusterSnapshotOperator": "airflow.providers.amazon.aws.operators.redshift_cluster.RedshiftDeleteClusterSnapshotOperator",
    "RedshiftResumeClusterOperator": "airflow.providers.amazon.aws.operators.redshift_cluster.RedshiftResumeClusterOperator",
    "RedshiftPauseClusterOperator": "airflow.providers.amazon.aws.operators.redshift_cluster.RedshiftPauseClusterOperator",
    "RedshiftDeleteClusterOperator": "airflow.providers.amazon.aws.operators.redshift_cluster.RedshiftDeleteClusterOperator",
    "RedshiftDataOperator": "airflow.providers.amazon.aws.operators.redshift_data.RedshiftDataOperator",
    "RedshiftClusterSensor": "airflow.providers.amazon.aws.sensors.redshift_cluster.RedshiftClusterSensor",
    # ── DMS ──
    "DmsCreateTaskOperator": "airflow.providers.amazon.aws.operators.dms.DmsCreateTaskOperator",
    "DmsDeleteTaskOperator": "airflow.providers.amazon.aws.operators.dms.DmsDeleteTaskOperator",
    "DmsDescribeTasksOperator": "airflow.providers.amazon.aws.operators.dms.DmsDescribeTasksOperator",
    "DmsStartTaskOperator": "airflow.providers.amazon.aws.operators.dms.DmsStartTaskOperator",
    "DmsStopTaskOperator": "airflow.providers.amazon.aws.operators.dms.DmsStopTaskOperator",
    "DmsTaskBaseSensor": "airflow.providers.amazon.aws.sensors.dms.DmsTaskBaseSensor",
    "DmsTaskCompletedSensor": "airflow.providers.amazon.aws.sensors.dms.DmsTaskCompletedSensor",
    # ── EC2 ──
    "EC2StartInstanceOperator": "airflow.providers.amazon.aws.operators.ec2.EC2StartInstanceOperator",
    "EC2StopInstanceOperator": "airflow.providers.amazon.aws.operators.ec2.EC2StopInstanceOperator",
    "EC2CreateInstanceOperator": "airflow.providers.amazon.aws.operators.ec2.EC2CreateInstanceOperator",
    "EC2TerminateInstanceOperator": "airflow.providers.amazon.aws.operators.ec2.EC2TerminateInstanceOperator",
    "EC2RebootInstanceOperator": "airflow.providers.amazon.aws.operators.ec2.EC2RebootInstanceOperator",
    "EC2HibernateInstanceOperator": "airflow.providers.amazon.aws.operators.ec2.EC2HibernateInstanceOperator",
    "EC2InstanceStateSensor": "airflow.providers.amazon.aws.sensors.ec2.EC2InstanceStateSensor",
    # ── SNS / SQS ──
    "SnsPublishOperator": "airflow.providers.amazon.aws.operators.sns.SnsPublishOperator",
    "SqsPublishOperator": "airflow.providers.amazon.aws.operators.sqs.SqsPublishOperator",
    "SqsSensor": "airflow.providers.amazon.aws.sensors.sqs.SqsSensor",
    # ── EventBridge ──
    "EventBridgePutEventsOperator": "airflow.providers.amazon.aws.operators.eventbridge.EventBridgePutEventsOperator",
    "EventBridgePutRuleOperator": "airflow.providers.amazon.aws.operators.eventbridge.EventBridgePutRuleOperator",
    "EventBridgeEnableRuleOperator": "airflow.providers.amazon.aws.operators.eventbridge.EventBridgeEnableRuleOperator",
    "EventBridgeDisableRuleOperator": "airflow.providers.amazon.aws.operators.eventbridge.EventBridgeDisableRuleOperator",
    # ── Comprehend ──
    "ComprehendBaseOperator": "airflow.providers.amazon.aws.operators.comprehend.ComprehendBaseOperator",
    "ComprehendStartPiiEntitiesDetectionJobOperator": "airflow.providers.amazon.aws.operators.comprehend.ComprehendStartPiiEntitiesDetectionJobOperator",
    "ComprehendCreateDocumentClassifierOperator": "airflow.providers.amazon.aws.operators.comprehend.ComprehendCreateDocumentClassifierOperator",
    "ComprehendBaseSensor": "airflow.providers.amazon.aws.sensors.comprehend.ComprehendBaseSensor",
    "ComprehendStartPiiEntitiesDetectionJobCompletedSensor": "airflow.providers.amazon.aws.sensors.comprehend.ComprehendStartPiiEntitiesDetectionJobCompletedSensor",
    "ComprehendCreateDocumentClassifierCompletedSensor": "airflow.providers.amazon.aws.sensors.comprehend.ComprehendCreateDocumentClassifierCompletedSensor",
    # ── Kinesis Analytics ──
    "KinesisAnalyticsV2CreateApplicationOperator": "airflow.providers.amazon.aws.operators.kinesis_analytics.KinesisAnalyticsV2CreateApplicationOperator",
    "KinesisAnalyticsV2StartApplicationOperator": "airflow.providers.amazon.aws.operators.kinesis_analytics.KinesisAnalyticsV2StartApplicationOperator",
    "KinesisAnalyticsV2StopApplicationOperator": "airflow.providers.amazon.aws.operators.kinesis_analytics.KinesisAnalyticsV2StopApplicationOperator",
    "KinesisAnalyticsV2BaseSensor": "airflow.providers.amazon.aws.sensors.kinesis_analytics.KinesisAnalyticsV2BaseSensor",
    "KinesisAnalyticsV2StartApplicationCompletedSensor": "airflow.providers.amazon.aws.sensors.kinesis_analytics.KinesisAnalyticsV2StartApplicationCompletedSensor",
    "KinesisAnalyticsV2StopApplicationCompletedSensor": "airflow.providers.amazon.aws.sensors.kinesis_analytics.KinesisAnalyticsV2StopApplicationCompletedSensor",
    # ── Neptune ──
    "NeptuneStartDbClusterOperator": "airflow.providers.amazon.aws.operators.neptune.NeptuneStartDbClusterOperator",
    "NeptuneStopDbClusterOperator": "airflow.providers.amazon.aws.operators.neptune.NeptuneStopDbClusterOperator",
    # ── Glacier ──
    "GlacierCreateJobOperator": "airflow.providers.amazon.aws.operators.glacier.GlacierCreateJobOperator",
    "GlacierUploadArchiveOperator": "airflow.providers.amazon.aws.operators.glacier.GlacierUploadArchiveOperator",
    "GlacierJobOperationSensor": "airflow.providers.amazon.aws.sensors.glacier.GlacierJobOperationSensor",
    # ── DataSync ──
    "DataSyncOperator": "airflow.providers.amazon.aws.operators.datasync.DataSyncOperator",
    # ── AppFlow ──
    "AppflowBaseOperator": "airflow.providers.amazon.aws.operators.appflow.AppflowBaseOperator",
    "AppflowRunOperator": "airflow.providers.amazon.aws.operators.appflow.AppflowRunOperator",
    "AppflowRunFullOperator": "airflow.providers.amazon.aws.operators.appflow.AppflowRunFullOperator",
    "AppflowRunBeforeOperator": "airflow.providers.amazon.aws.operators.appflow.AppflowRunBeforeOperator",
    "AppflowRunAfterOperator": "airflow.providers.amazon.aws.operators.appflow.AppflowRunAfterOperator",
    "AppflowRunDailyOperator": "airflow.providers.amazon.aws.operators.appflow.AppflowRunDailyOperator",
    "AppflowRecordsShortCircuitOperator": "airflow.providers.amazon.aws.operators.appflow.AppflowRecordsShortCircuitOperator",
    # ── QuickSight ──
    "QuickSightCreateIngestionOperator": "airflow.providers.amazon.aws.operators.quicksight.QuickSightCreateIngestionOperator",
    "QuickSightSensor": "airflow.providers.amazon.aws.sensors.quicksight.QuickSightSensor",
    # ── DynamoDB ──
    "DynamoDBValueSensor": "airflow.providers.amazon.aws.sensors.dynamodb.DynamoDBValueSensor",
    # ── OpenSearch Serverless ──
    "OpenSearchServerlessCollectionActiveSensor": "airflow.providers.amazon.aws.sensors.opensearch_serverless.OpenSearchServerlessCollectionActiveSensor",
    # ── Base sensors ──
    "AwsBaseSensor": "airflow.providers.amazon.aws.sensors.base_aws.AwsBaseSensor",
}

# Reverse lookup: FQN -> short name
_FQN_TO_SHORT = {v: k for k, v in SUPPORTED_OPERATORS.items()}

# Set of all accepted operator values (both short names and FQNs)
ALLOWED_OPERATOR_VALUES = set(SUPPORTED_OPERATORS.keys()) | set(SUPPORTED_OPERATORS.values())
